package model;
// Generated 22/06/2017 19:29:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbPrestador generated by hbm2java
 */
public class TbPrestador  implements java.io.Serializable {


     private Integer idtPrestador;
     private TbUsuario tbUsuario;
     private TtTipoPrestador ttTipoPrestador;
     private String enderecoEmpresa;
     private int telComercialPrestador;
     private String tipoPrestador;
     private Integer cpfPrestador;
     private Integer cnpjPrestador;
     private String nmeFantasiaPrestador;
     private Set<TbServico> tbServicos = new HashSet<TbServico>(0);
     private Set<TtTipoPagamento> ttTipoPagamentos = new HashSet<TtTipoPagamento>(0);
     private Set<TaMensagem> taMensagems = new HashSet<TaMensagem>(0);

    public TbPrestador() {
    }

	
    public TbPrestador(TbUsuario tbUsuario, TtTipoPrestador ttTipoPrestador, String enderecoEmpresa, int telComercialPrestador, String tipoPrestador) {
        this.tbUsuario = tbUsuario;
        this.ttTipoPrestador = ttTipoPrestador;
        this.enderecoEmpresa = enderecoEmpresa;
        this.telComercialPrestador = telComercialPrestador;
        this.tipoPrestador = tipoPrestador;
    }
    public TbPrestador(TbUsuario tbUsuario, TtTipoPrestador ttTipoPrestador, String enderecoEmpresa, int telComercialPrestador, String tipoPrestador, Integer cpfPrestador, Integer cnpjPrestador, String nmeFantasiaPrestador, Set<TbServico> tbServicos, Set<TtTipoPagamento> ttTipoPagamentos, Set<TaMensagem> taMensagems) {
       this.tbUsuario = tbUsuario;
       this.ttTipoPrestador = ttTipoPrestador;
       this.enderecoEmpresa = enderecoEmpresa;
       this.telComercialPrestador = telComercialPrestador;
       this.tipoPrestador = tipoPrestador;
       this.cpfPrestador = cpfPrestador;
       this.cnpjPrestador = cnpjPrestador;
       this.nmeFantasiaPrestador = nmeFantasiaPrestador;
       this.tbServicos = tbServicos;
       this.ttTipoPagamentos = ttTipoPagamentos;
       this.taMensagems = taMensagems;
    }
   
    public Integer getIdtPrestador() {
        return this.idtPrestador;
    }
    
    public void setIdtPrestador(Integer idtPrestador) {
        this.idtPrestador = idtPrestador;
    }
    public TbUsuario getTbUsuario() {
        return this.tbUsuario;
    }
    
    public void setTbUsuario(TbUsuario tbUsuario) {
        this.tbUsuario = tbUsuario;
    }
    public TtTipoPrestador getTtTipoPrestador() {
        return this.ttTipoPrestador;
    }
    
    public void setTtTipoPrestador(TtTipoPrestador ttTipoPrestador) {
        this.ttTipoPrestador = ttTipoPrestador;
    }
    public String getEnderecoEmpresa() {
        return this.enderecoEmpresa;
    }
    
    public void setEnderecoEmpresa(String enderecoEmpresa) {
        this.enderecoEmpresa = enderecoEmpresa;
    }
    public int getTelComercialPrestador() {
        return this.telComercialPrestador;
    }
    
    public void setTelComercialPrestador(int telComercialPrestador) {
        this.telComercialPrestador = telComercialPrestador;
    }
    public String getTipoPrestador() {
        return this.tipoPrestador;
    }
    
    public void setTipoPrestador(String tipoPrestador) {
        this.tipoPrestador = tipoPrestador;
    }
    public Integer getCpfPrestador() {
        return this.cpfPrestador;
    }
    
    public void setCpfPrestador(Integer cpfPrestador) {
        this.cpfPrestador = cpfPrestador;
    }
    public Integer getCnpjPrestador() {
        return this.cnpjPrestador;
    }
    
    public void setCnpjPrestador(Integer cnpjPrestador) {
        this.cnpjPrestador = cnpjPrestador;
    }
    public String getNmeFantasiaPrestador() {
        return this.nmeFantasiaPrestador;
    }
    
    public void setNmeFantasiaPrestador(String nmeFantasiaPrestador) {
        this.nmeFantasiaPrestador = nmeFantasiaPrestador;
    }
    public Set<TbServico> getTbServicos() {
        return this.tbServicos;
    }
    
    public void setTbServicos(Set<TbServico> tbServicos) {
        this.tbServicos = tbServicos;
    }
    public Set<TtTipoPagamento> getTtTipoPagamentos() {
        return this.ttTipoPagamentos;
    }
    
    public void setTtTipoPagamentos(Set<TtTipoPagamento> ttTipoPagamentos) {
        this.ttTipoPagamentos = ttTipoPagamentos;
    }
    public Set<TaMensagem> getTaMensagems() {
        return this.taMensagems;
    }
    
    public void setTaMensagems(Set<TaMensagem> taMensagems) {
        this.taMensagems = taMensagems;
    }




}


