package model;
// Generated 22/06/2017 19:29:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TbServico generated by hbm2java
 */
public class TbServico  implements java.io.Serializable {


     private Integer idtServico;
     private TbPrestador tbPrestador;
     private TtTipoServico ttTipoServico;
     private String nmeServico;
     private BigDecimal precoServico;
     private String descricaoServico;
     private String foto;
     private Set<TtAgenda> ttAgendas = new HashSet<TtAgenda>(0);
     private Set<TaServicoPrestado> taServicoPrestados = new HashSet<TaServicoPrestado>(0);

    public TbServico() {
    }

	
    public TbServico(TbPrestador tbPrestador, TtTipoServico ttTipoServico, String nmeServico, BigDecimal precoServico, String descricaoServico, String foto) {
        this.tbPrestador = tbPrestador;
        this.ttTipoServico = ttTipoServico;
        this.nmeServico = nmeServico;
        this.precoServico = precoServico;
        this.descricaoServico = descricaoServico;
        this.foto = foto;
    }
    public TbServico(TbPrestador tbPrestador, TtTipoServico ttTipoServico, String nmeServico, BigDecimal precoServico, String descricaoServico, String foto, Set<TtAgenda> ttAgendas, Set<TaServicoPrestado> taServicoPrestados) {
       this.tbPrestador = tbPrestador;
       this.ttTipoServico = ttTipoServico;
       this.nmeServico = nmeServico;
       this.precoServico = precoServico;
       this.descricaoServico = descricaoServico;
       this.foto = foto;
       this.ttAgendas = ttAgendas;
       this.taServicoPrestados = taServicoPrestados;
    }
   
    public Integer getIdtServico() {
        return this.idtServico;
    }
    
    public void setIdtServico(Integer idtServico) {
        this.idtServico = idtServico;
    }
    public TbPrestador getTbPrestador() {
        return this.tbPrestador;
    }
    
    public void setTbPrestador(TbPrestador tbPrestador) {
        this.tbPrestador = tbPrestador;
    }
    public TtTipoServico getTtTipoServico() {
        return this.ttTipoServico;
    }
    
    public void setTtTipoServico(TtTipoServico ttTipoServico) {
        this.ttTipoServico = ttTipoServico;
    }
    public String getNmeServico() {
        return this.nmeServico;
    }
    
    public void setNmeServico(String nmeServico) {
        this.nmeServico = nmeServico;
    }
    public BigDecimal getPrecoServico() {
        return this.precoServico;
    }
    
    public void setPrecoServico(BigDecimal precoServico) {
        this.precoServico = precoServico;
    }
    public String getDescricaoServico() {
        return this.descricaoServico;
    }
    
    public void setDescricaoServico(String descricaoServico) {
        this.descricaoServico = descricaoServico;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public Set<TtAgenda> getTtAgendas() {
        return this.ttAgendas;
    }
    
    public void setTtAgendas(Set<TtAgenda> ttAgendas) {
        this.ttAgendas = ttAgendas;
    }
    public Set<TaServicoPrestado> getTaServicoPrestados() {
        return this.taServicoPrestados;
    }
    
    public void setTaServicoPrestados(Set<TaServicoPrestado> taServicoPrestados) {
        this.taServicoPrestados = taServicoPrestados;
    }




}


