package model;
// Generated 22/06/2017 19:29:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbUsuario generated by hbm2java
 */
public class TbUsuario  implements java.io.Serializable {


     private int idtUsuario;
     private String nmeUsuario;
     private String emailUsuario;
     private String senhaUsuario;
     private int telUsuario;
     private int cepUsuario;
     private String enderecoUsuario;
     private String complementoEnderecoUsuario;
     private String numEnderecoUsuario;
     private String tipoUsuario;
     private Set<TbPrestador> tbPrestadors = new HashSet<TbPrestador>(0);
     private Set<TaServicoPrestado> taServicoPrestados = new HashSet<TaServicoPrestado>(0);
     private Set<TaMensagem> taMensagems = new HashSet<TaMensagem>(0);

    public TbUsuario() {
    }

	
    public TbUsuario(int idtUsuario, String nmeUsuario, String emailUsuario, String senhaUsuario, int telUsuario, int cepUsuario, String enderecoUsuario, String complementoEnderecoUsuario, String numEnderecoUsuario, String tipoUsuario) {
        this.idtUsuario = idtUsuario;
        this.nmeUsuario = nmeUsuario;
        this.emailUsuario = emailUsuario;
        this.senhaUsuario = senhaUsuario;
        this.telUsuario = telUsuario;
        this.cepUsuario = cepUsuario;
        this.enderecoUsuario = enderecoUsuario;
        this.complementoEnderecoUsuario = complementoEnderecoUsuario;
        this.numEnderecoUsuario = numEnderecoUsuario;
        this.tipoUsuario = tipoUsuario;
    }
    public TbUsuario(int idtUsuario, String nmeUsuario, String emailUsuario, String senhaUsuario, int telUsuario, int cepUsuario, String enderecoUsuario, String complementoEnderecoUsuario, String numEnderecoUsuario, String tipoUsuario, Set<TbPrestador> tbPrestadors, Set<TaServicoPrestado> taServicoPrestados, Set<TaMensagem> taMensagems) {
       this.idtUsuario = idtUsuario;
       this.nmeUsuario = nmeUsuario;
       this.emailUsuario = emailUsuario;
       this.senhaUsuario = senhaUsuario;
       this.telUsuario = telUsuario;
       this.cepUsuario = cepUsuario;
       this.enderecoUsuario = enderecoUsuario;
       this.complementoEnderecoUsuario = complementoEnderecoUsuario;
       this.numEnderecoUsuario = numEnderecoUsuario;
       this.tipoUsuario = tipoUsuario;
       this.tbPrestadors = tbPrestadors;
       this.taServicoPrestados = taServicoPrestados;
       this.taMensagems = taMensagems;
    }
   
    public int getIdtUsuario() {
        return this.idtUsuario;
    }
    
    public void setIdtUsuario(int idtUsuario) {
        this.idtUsuario = idtUsuario;
    }
    public String getNmeUsuario() {
        return this.nmeUsuario;
    }
    
    public void setNmeUsuario(String nmeUsuario) {
        this.nmeUsuario = nmeUsuario;
    }
    public String getEmailUsuario() {
        return this.emailUsuario;
    }
    
    public void setEmailUsuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }
    public String getSenhaUsuario() {
        return this.senhaUsuario;
    }
    
    public void setSenhaUsuario(String senhaUsuario) {
        this.senhaUsuario = senhaUsuario;
    }
    public int getTelUsuario() {
        return this.telUsuario;
    }
    
    public void setTelUsuario(int telUsuario) {
        this.telUsuario = telUsuario;
    }
    public int getCepUsuario() {
        return this.cepUsuario;
    }
    
    public void setCepUsuario(int cepUsuario) {
        this.cepUsuario = cepUsuario;
    }
    public String getEnderecoUsuario() {
        return this.enderecoUsuario;
    }
    
    public void setEnderecoUsuario(String enderecoUsuario) {
        this.enderecoUsuario = enderecoUsuario;
    }
    public String getComplementoEnderecoUsuario() {
        return this.complementoEnderecoUsuario;
    }
    
    public void setComplementoEnderecoUsuario(String complementoEnderecoUsuario) {
        this.complementoEnderecoUsuario = complementoEnderecoUsuario;
    }
    public String getNumEnderecoUsuario() {
        return this.numEnderecoUsuario;
    }
    
    public void setNumEnderecoUsuario(String numEnderecoUsuario) {
        this.numEnderecoUsuario = numEnderecoUsuario;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public Set<TbPrestador> getTbPrestadors() {
        return this.tbPrestadors;
    }
    
    public void setTbPrestadors(Set<TbPrestador> tbPrestadors) {
        this.tbPrestadors = tbPrestadors;
    }
    public Set<TaServicoPrestado> getTaServicoPrestados() {
        return this.taServicoPrestados;
    }
    
    public void setTaServicoPrestados(Set<TaServicoPrestado> taServicoPrestados) {
        this.taServicoPrestados = taServicoPrestados;
    }
    public Set<TaMensagem> getTaMensagems() {
        return this.taMensagems;
    }
    
    public void setTaMensagems(Set<TaMensagem> taMensagems) {
        this.taMensagems = taMensagems;
    }




}


